//
//  CTLoginViewUI.h
//  CartTracker
//
//  Created by Andres Ruggiero on 12/8/14.
//  Copyright (c) 2014 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface CTLoginViewUI : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;
+ (void)drawCanvas3;

@end
