//
//  CTLoginViewUI.m
//  CartTracker
//
//  Created by Andres Ruggiero on 12/8/14.
//  Copyright (c) 2014 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "CTLoginViewUI.h"


@implementation CTLoginViewUI

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.09 green: 0.2 blue: 0.357 alpha: 1];

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(0, 0, 240, 120) cornerRadius: 7];
    [color setFill];
    [rectanglePath fill];
}

+ (void)drawCanvas2
{
    //// Color Declarations
    UIColor* color2 = [UIColor colorWithRed: 0.982 green: 0.985 blue: 0.975 alpha: 1];

    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(0, 0, 131, 18) cornerRadius: 7];
    [color2 setFill];
    [rectangle2Path fill];
}

+ (void)drawCanvas3
{

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(0.5, 0.5, 101, 102)];
    [UIColor.grayColor setStroke];
    ovalPath.lineWidth = 1;
    [ovalPath stroke];

}

@end
